### ISSUE TITLE
getRun function is not working as expected

### ISSUE THREAD

**Issue by krthknan** [mvndaai/testrail-promise#18]
Below is my code :

var runId;
var TestRail = require("testrail-promise");
var testrail = new TestRail("https://testrail.companyName.com/", "userId", "Password");

testrail.addRun({"project_id":"71", "suite_id":1558}).then(function(body){
			JSON.stringify(body);
			runId=body.id;
			console.log( "Inside AddRun : " + runId); //Returns RunID properly
		});

testrail.getRun({"run_id":runId}).then(function(body){                          //Returns "Undefined" for runId
			console.log( "Inside GetRun : " + runId); 
			console.log(body);
		});

Output :
D:\Workspace\Test-Rail>protractor config.js
[12:33:41] I/launcher - Running 1 instances of WebDriver
[12:33:41] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
Started
**Inside GetRun : undefined**
**{ error: 'Field :run is not a valid ID.' }**

1 spec, 0 failures
Finished in 3.573 seconds

[12:33:47] I/launcher - 0 instance(s) of WebDriver still running
[12:33:47] I/launcher - chrome #01 passed

**Comment by krthknan** [comment]
How to break the promise ?

**Comment by mvndaai** [comment]
Since they are separate promises just because they are after each other, doesn't mean that they happen in order.

A quick fix would be to just move the second function into a new promise

```
testrail.addRun({"project_id":"71", "suite_id":1558}).then(function(body){
    JSON.stringify(body);
    return runId=body.id;
})
.then(function(runId) {
    return testrail.getRun({"run_id":runId})
})
.then(function(body){ //Returns "Undefined" for runId
    console.log( "Inside GetRun : " + runId);
    console.log(body);
});
```

You might want to look into `async/await` to not need to have all the `then` functions in your code. I haven't used it much but here are some pages to get more info:
https://hackernoon.com/javascript-promises-and-why-async-await-wins-the-battle-4fc9d15d509f
https://javascript.info/async-await
https://medium.com/@bluepnume/learn-about-promises-before-you-start-using-async-await-eb148164a9c8

**Comment by krthknan** [comment]
Thanks for your comments, I'll look into it
